<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.test.automation.uiAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials" tests="4" time="7.289" ignored="0" failures="1" timestamp="18 Jan 2018 20:14:04 GMT" skipped="3" hostname="Home_PC" errors="0">
  <testcase name="verifyLoginWithInvalidCredentials" time="1.718" classname="com.test.automation.uiAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials">
    <skipped/>
  </testcase> <!-- verifyLoginWithInvalidCredentials -->
  <testcase name="verifyLoginWithInvalidCredentials" time="2.330" classname="com.test.automation.uiAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials">
    <skipped/>
  </testcase> <!-- verifyLoginWithInvalidCredentials -->
  <testcase name="verifyLoginWithInvalidCredentials" time="1.672" classname="com.test.automation.uiAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials">
    <skipped/>
  </testcase> <!-- verifyLoginWithInvalidCredentials -->
  <testcase name="verifyLoginWithInvalidCredentials" time="1.569" classname="com.test.automation.uiAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials">
    <failure type="java.lang.AssertionError" message="expected [TestAuthentication failed.] but found [Authentication failed.]">
      <![CDATA[java.lang.AssertionError: expected [TestAuthentication failed.] but found [Authentication failed.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.test.automation.uiAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials.verifyLoginWithInvalidCredentials(TC001_VerifyLoginWithInvalidCredentials.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- verifyLoginWithInvalidCredentials -->
</testsuite> <!-- com.test.automation.uiAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials -->
